<script setup lang="ts">
import type { TwoFactorStatus } from '~/utils/types'

/**
 * Account → two-factor authentication: turn on (scan QR → confirm a code → save recovery codes),
 * turn off, or replace the recovery codes. Turning off / new codes need a current code.
 */
const { t } = useI18n()
const api = useApi()
const { fetchMe } = useAuth()
const { data: status, refresh } = await useAsyncData('auth-2fa', () => api<TwoFactorStatus>('/auth/2fa'))

const step = ref<'idle' | 'setup' | 'codes' | 'disable' | 'regenerate'>('idle')
const setup = ref<{ secret: string; otpauth_url: string; qr_svg: string } | null>(null)
const codes = ref<string[]>([])
const code = ref('')
const busy = ref(false)
const error = ref('')
const copied = ref(false)

function reset(to: typeof step.value = 'idle') {
  step.value = to
  code.value = error.value = ''
}

async function run(fn: () => Promise<void>) {
  error.value = ''
  busy.value = true
  try {
    await fn()
  } catch (e) {
    error.value = apiError(e)
  } finally {
    busy.value = false
  }
}

const start = () =>
  run(async () => {
    setup.value = await api('/auth/2fa/setup', { method: 'POST' })
    reset('setup')
  })

const confirmSetup = () =>
  run(async () => {
    const r = await api<{ recovery_codes: string[] }>('/auth/2fa/enable', { method: 'POST', body: { code: code.value } })
    codes.value = r.recovery_codes
    setup.value = null
    reset('codes')
    await Promise.all([refresh(), fetchMe()])
  })

const turnOff = () =>
  run(async () => {
    await api('/auth/2fa/disable', { method: 'POST', body: { code: code.value } })
    reset()
    await Promise.all([refresh(), fetchMe()])
  })

const newCodes = () =>
  run(async () => {
    const r = await api<{ recovery_codes: string[] }>('/auth/2fa/recovery-codes', { method: 'POST', body: { code: code.value } })
    codes.value = r.recovery_codes
    reset('codes')
    await refresh()
  })

async function copyCodes() {
  await navigator.clipboard.writeText(codes.value.join('\n'))
  copied.value = true
  setTimeout(() => (copied.value = false), 2000)
}
function downloadCodes() {
  const blob = new Blob([`zaokaiy recovery codes\n\n${codes.value.join('\n')}\n`], { type: 'text/plain' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = 'zaokaiy-recovery-codes.txt'
  a.click()
  URL.revokeObjectURL(a.href)
}
function doneWithCodes() {
  codes.value = []
  reset()
}
</script>

<template>
  <section class="card p-5">
    <div class="flex items-start gap-3">
      <div class="min-w-0 flex-1">
        <h2 class="font-bold">{{ t('auth.twoFactor.settingsTitle') }}</h2>
        <p class="text-sm text-muted">{{ t('auth.twoFactor.settingsHint') }}</p>
      </div>
      <span
        class="shrink-0 rounded-full px-2.5 py-1 text-xs font-bold"
        :class="status?.enabled ? 'bg-mint-500/15 text-mint-500' : 'bg-field text-muted'"
      >{{ status?.enabled ? t('auth.twoFactor.on') : t('auth.twoFactor.off') }}</span>
    </div>

    <!-- Recovery codes, shown once -->
    <div v-if="step === 'codes'" class="mt-4 space-y-3">
      <p class="rounded-xl bg-sun-400/15 px-3 py-2 text-sm text-amber-800">{{ t('auth.twoFactor.codesWarning') }}</p>
      <ul class="grid grid-cols-2 gap-2 rounded-xl border border-line p-3 font-mono text-sm">
        <li v-for="c in codes" :key="c">{{ c }}</li>
      </ul>
      <div class="flex flex-wrap gap-2">
        <UButton color="neutral" variant="soft" size="sm" @click="copyCodes">{{ copied ? t('auth.twoFactor.copied') : t('auth.twoFactor.copy') }}</UButton>
        <UButton color="neutral" variant="soft" size="sm" @click="downloadCodes">{{ t('auth.twoFactor.download') }}</UButton>
        <UButton size="sm" class="ml-auto" @click="doneWithCodes">{{ t('auth.twoFactor.savedCodes') }}</UButton>
      </div>
    </div>

    <!-- Setup: scan, then confirm a code -->
    <form v-else-if="step === 'setup' && setup" class="mt-4 space-y-3" @submit.prevent="confirmSetup">
      <ol class="list-decimal space-y-1 pl-5 text-sm">
        <li>{{ t('auth.twoFactor.step1') }}</li>
        <li>{{ t('auth.twoFactor.step2') }}</li>
      </ol>
      <!-- eslint-disable-next-line vue/no-v-html -- SVG generated by our API -->
      <div class="mx-auto w-52 rounded-xl bg-white p-2 [&>svg]:h-auto [&>svg]:w-full" v-html="setup.qr_svg" />
      <details class="text-center text-xs text-muted">
        <summary class="cursor-pointer">{{ t('auth.twoFactor.cantScan') }}</summary>
        <code class="mt-2 block select-all break-all font-mono text-sm text-ink">{{ setup.secret }}</code>
      </details>
      <UInput v-model="code" class="text-center font-mono text-xl tracking-[0.4em]" inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="••••••" :aria-label="t('auth.twoFactor.code')" required />
      <p v-if="error" class="text-sm text-brand-700">{{ error }}</p>
      <div class="flex gap-2">
        <UButton color="neutral" variant="soft" type="button" @click="reset()">{{ t('common.back') }}</UButton>
        <UButton type="submit" class="flex-1" :disabled="busy || code.replace(/\D/g, '').length !== 6">{{ t('auth.twoFactor.confirm') }}</UButton>
      </div>
    </form>

    <!-- Turn off / new recovery codes: prove possession first -->
    <form v-else-if="step === 'disable' || step === 'regenerate'" class="mt-4 space-y-3" @submit.prevent="step === 'disable' ? turnOff() : newCodes()">
      <p class="text-sm">{{ step === 'disable' ? t('auth.twoFactor.disablePrompt') : t('auth.twoFactor.regeneratePrompt') }}</p>
      <UInput v-model="code" class="font-mono" autocomplete="one-time-code" :placeholder="t('auth.twoFactor.codeOrRecovery')" required />
      <p v-if="error" class="text-sm text-brand-700">{{ error }}</p>
      <div class="flex gap-2">
        <UButton color="neutral" variant="soft" type="button" @click="reset()">{{ t('common.back') }}</UButton>
        <UButton type="submit" class="flex-1" :color="step === 'disable' ? 'error' : 'primary'" :disabled="busy || code.trim().length < 6">
          {{ step === 'disable' ? t('auth.twoFactor.disable') : t('auth.twoFactor.regenerate') }}
        </UButton>
      </div>
    </form>

    <div v-else class="mt-4">
      <template v-if="status?.enabled">
        <p class="text-sm text-muted">
          {{ t('auth.twoFactor.enabledSince', { date: fmtDate(status.enabled_at!) }) }} ·
          <span :class="{ 'font-semibold text-brand-700': status.recovery_codes_left <= 2 }">{{ t('auth.twoFactor.codesLeft', { n: status.recovery_codes_left }) }}</span>
        </p>
        <div class="mt-3 flex flex-wrap gap-2">
          <UButton color="neutral" variant="soft" size="sm" @click="reset('regenerate')">{{ t('auth.twoFactor.regenerate') }}</UButton>
          <UButton color="error" variant="soft" size="sm" @click="reset('disable')">{{ t('auth.twoFactor.disable') }}</UButton>
        </div>
      </template>
      <UButton v-else :disabled="busy" @click="start">{{ t('auth.twoFactor.enable') }}</UButton>
      <p v-if="error" class="mt-2 text-sm text-brand-700">{{ error }}</p>
    </div>
  </section>
</template>
